### ISSUE TITLE
[Feature Request] Access to harmonized scoring files

### ISSUE THREAD

**Issue by mglev1n** [ramiromagno/quincunx#1]
The PGS Catalog now provides "harmonized" scoring files in both GRCh37 and GRCh38 formats: https://www.pgscatalog.org/downloads/. These files are located within the "Harmonized" folder on the PGS Catalog FTP server: `ftp://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS######/ScoringFiles/Harmonized/`. It would be great if the `read_scoring_file` function could be adapted to allow the user to download these harmonized files.

**Comment by ramiromagno** [comment]
Hi @mglev1n,

That's a great idea!

I will look into it in the next days. Also, feel free to contribute if you feel like it :)

**Comment by ramiromagno** [comment]
Hi @mglev1n,

Could you try the new development version?

Install:

```
remotes::install_github("ramiromagno/quincunx", ref = "001-read-harmonized-pgs")
```

Usage:

```
read_scoring_file("PGS000001", harmonized = TRUE, assembly = "GRCh37")
read_scoring_file("PGS000001", harmonized = TRUE, assembly = "GRCh38")
```
